"""Minimal logger protocol for dependencies. Depend on the protocol, not ``SystemLogger``."""

from __future__ import annotations

from typing import Any, Protocol


class LoggerProtocol(Protocol):
    """Minimal logger surface: debug, info, warning, error, exception. No GUI specifics."""

    def debug(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def info(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def error(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def exception(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
